[mypy]
python_version = 3.13
explicit_package_bases = True
ignore_missing_imports = True
check_untyped_defs = True

[mypy-app.*]
ignore_errors = False

[mypy-dateutil.*]
ignore_missing_imports = True
