"""add donor grantee relationship table

Revision ID: 8f014bdb3a61
Revises: 000003
Create Date: 2026-08-04 13:35:41.987849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from shared.db.type_decorators import GUID

# revision identifiers, used by Alembic.
revision: str = "000004"
down_revision: Union[str, Sequence[str], None] = "000003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "donor_grantees",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("donor_id", GUID(), nullable=False),
        sa.Column("grantee_id", GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", GUID(), nullable=True),
        sa.Column("updated_by", GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["donor_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grantee_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("donor_id", "grantee_id", name="uq_donor_grantees_donor_id_grantee_id"),
    )
    op.create_index(op.f("ix_donor_grantees_id"), "donor_grantees", ["id"], unique=False)
    op.create_index(
        op.f("ix_donor_grantees_donor_id"), "donor_grantees", ["donor_id"], unique=False
    )
    op.create_index(
        op.f("ix_donor_grantees_grantee_id"), "donor_grantees", ["grantee_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_donor_grantees_grantee_id"), table_name="donor_grantees")
    op.drop_index(op.f("ix_donor_grantees_donor_id"), table_name="donor_grantees")
    op.drop_index(op.f("ix_donor_grantees_id"), table_name="donor_grantees")
    op.drop_table("donor_grantees")
    # ### end Alembic commands ###
